version: '3.4'

services:
  nginx:
    image: nginx:1.13.10-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default-ssl/:/etc/nginx/conf.d
      - ./certs/:/certs/
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app

  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: "/usr/src/app"
    command: gunicorn -w 2 -b :8000 app:app
    restart: on-failure:5
    #env_file:
      #- .env
    environment:
      - LANG=C.UTF-8
      - APP_ENVIRONMENT=production
